export { default as FillGrid } from './grid_fillGrid'
export { default as Shuffle } from './shuffleArray'
export { isInRow as isInRow }  from './row_col_check'
export { isInCol as isInCol }  from './row_col_check'
export { default as identifySquare} from './identifySquare'